= reveal.adoc
:author: Jason Lund

Example of how to use asciidoctor-reveal.js and reveal.js while keeping a clean repository for your presentation.

== Asciidoctor / Ruby / Bundler

=== Pre-requisites
. ruby install
. rubygems installed
. bundler ruby gem installed
. asciidoctor gem installed
. asciidoctor-revealjs gem installed

Assuming you have Ruby installed and the gem *bundler*.

=== bundle install
bundle instructions on the Asciidoctor reveal.js site use the following command.

[source]
bundle config --local github.https true

[source]
bundle --path=.bundle/gems --binstubs=.bundle/.bin

But based on warnings in the command line when this command is executed, it is better to use the following (multiple commands separated by a semicolon can be executed on one line in powershell).

[source]
bundle config --local github.https true; bundle config set --local path '.bundle/gems': bundle binstubs --all; bundle

[source]
bundle --binstubs=.bundle/.bin

== Asciidoctor.js / JavaScript (Node.js) / npm

Haven't tried this implementation yet.
Need to setup a different branch for an example repo with that.

== Initialize submodules

[source]
----
git submodule update --init
----


== Compile presentation

[source]
----
bundle exec asciidoctor-revealjs PRESENTATION.adoc
----
